// Generated by RevEngAPI for class io.netty.handler.ssl.OpenSslServerSessionContext
package io.netty.handler.ssl;

final public class OpenSslServerSessionContext {

	// Constructors
	OpenSslServerSessionContext(io.netty.handler.ssl.ReferenceCountedOpenSslContext arg0, io.netty.handler.ssl.OpenSslKeyMaterialProvider arg1) {
	}
	// Methods
	public void setSessionCacheSize(int arg0) {
	return 0;
	}
	public int getSessionCacheSize() {
	return 0;
	}
	public void setSessionCacheEnabled(boolean arg0) {
	return 0;
	}
	public boolean isSessionCacheEnabled() {
	return false;
	}
	public boolean setSessionIdContext([B arg0) {
	return false;
	}
	public int getSessionTimeout() {
	return 0;
	}
	public void setSessionTimeout(int arg0) {
	return 0;
	}
}
