// Generated by RevEngAPI for class io.netty.handler.traffic.ChannelTrafficShapingHandler
package io.netty.handler.traffic;

public class ChannelTrafficShapingHandler {

	// Constructors
	public ChannelTrafficShapingHandler(long arg0, long arg1, long arg2, long arg3) {
	}	public ChannelTrafficShapingHandler(long arg0, long arg1, long arg2) {
	}	public ChannelTrafficShapingHandler(long arg0, long arg1) {
	}	public ChannelTrafficShapingHandler(long arg0) {
	}
	// Methods
	void submitWrite(io.netty.channel.ChannelHandlerContext arg0, java.lang.Object arg1, long arg2, long arg3, long arg4, io.netty.channel.ChannelPromise arg5) {
	return 0;
	}
	public long queueSize() {
	return 0;
	}
	public void handlerAdded(io.netty.channel.ChannelHandlerContext arg0) {
	return 0;
	}
	public void handlerRemoved(io.netty.channel.ChannelHandlerContext arg0) {
	return 0;
	}

	// Fields
}
