// Generated by RevEngAPI for class io.netty.handler.ipfilter.UniqueIpFilter
package io.netty.handler.ipfilter;

public class UniqueIpFilter {

	// Constructors
	public UniqueIpFilter() {
	}
	// Methods
	protected boolean accept(io.netty.channel.ChannelHandlerContext arg0, java.net.InetSocketAddress arg1) {
	return false;
	}
	protected volatile boolean accept(io.netty.channel.ChannelHandlerContext arg0, java.net.SocketAddress arg1) {
	return false;
	}

	// Fields
}
